// Generated by CoffeeScript 1.9.2
(function() {
  var app, chatServer, express, router, server;

  express = require('express');

  router = express.Router();

  app = express();

  server = require('http').createServer(app);

  chatServer = require('socket.io').listen(server);

  router.get('/', function(req, res, next) {
    return res.render('index', {
      title: 'Node-chat'
    });
  });

  chatServer.on('connection', function(socket) {
    console.log('socket established');
    return socket.emit('news', {
      hello: 'world'
    });
  });

  module.exports = router;

}).call(this);
