// Generated by CoffeeScript 1.9.2
(function() {
  var app, chatServer, express, io, server;

  express = require('express');

  app = express();

  server = app.listen(8080);

  io = require('socket.io');

  chatServer = io.Server(server, {
    path: '/socketest.io'
  });

  module["export"] = chatServer;

}).call(this);
